"""
Pattern Agent:
Evaluates flow sequence anomalies, skipped intermediate pages, missing asset
requests (CSS/JS/images), dwell time on intermediate screens, and isTrusted event checks.
Output: pattern_score (float, 0.0 to 1.0, higher = more bot-like)
"""
from typing import Dict, Any

def score_pattern(flow_context: Dict[str, Any]) -> float:
    """
    Evaluates step sequencing, navigation dwell time, and synthetic event trust.
    """
    if not flow_context:
        return 0.1

    risk_score = 0.0

    # 1. isTrusted event check (client-side synthesized dispatchEvent)
    is_trusted = flow_context.get("is_trusted")
    if is_trusted is False:
        # Client input was generated by extension autofill or synthetic JS event
        risk_score += 0.60
    elif is_trusted is True:
        risk_score -= 0.10

    # 2. Sequence anomalies (skipped steps)
    skipped_steps = flow_context.get("skipped_steps") or flow_context.get("sequence_anomaly")
    if skipped_steps:
        risk_score += 0.50

    # 3. Dwell time on intermediate screen (in milliseconds)
    dwell_time_ms = flow_context.get("dwell_time_ms")
    if dwell_time_ms is not None:
        if dwell_time_ms < 150:
            # 0 or near-0 dwell time on intermediate screen
            risk_score += 0.40
        elif 800 <= dwell_time_ms <= 30000:
            risk_score -= 0.15

    # 4. Missing page assets check (API call without prior static asset fetches)
    if flow_context.get("missing_assets") is True:
        risk_score += 0.30

    return max(0.0, min(1.0, risk_score))
